# Generated by Django 6.1 on 2026-08-27 02:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordAnalysisLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('longitud', models.PositiveIntegerField()),
                ('tiene_mayusculas', models.BooleanField(default=False)),
                ('tiene_minusculas', models.BooleanField(default=False)),
                ('tiene_numeros', models.BooleanField(default=False)),
                ('tiene_simbolos', models.BooleanField(default=False)),
                ('entropia_bits', models.FloatField(default=0)),
                ('fortaleza', models.CharField(choices=[('muy_debil', 'Muy débil'), ('debil', 'Débil'), ('media', 'Media'), ('fuerte', 'Fuerte'), ('muy_fuerte', 'Muy fuerte')], max_length=20)),
                ('fue_filtrada', models.BooleanField(blank=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='password_analysis_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Análisis de contraseña',
                'verbose_name_plural': 'Análisis de contraseñas',
                'ordering': ['-creado'],
            },
        ),
    ]
