# Generated by Django 6.1 on 2026-08-24 19:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('nmap_fast', 'Rápido (puertos comunes)'), ('nmap_full', 'Completo (todos los puertos)')], default='nmap_fast', max_length=20)),
                ('estado', models.CharField(choices=[('pending', 'Pendiente'), ('running', 'En progreso'), ('done', 'Completado'), ('error', 'Error')], default='pending', max_length=20)),
                ('resultado', models.TextField(blank=True, default='')),
                ('error_msg', models.TextField(blank=True, default='')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creado'],
            },
        ),
    ]
