# Generated by Django 6.1 on 2026-08-25 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scan_network', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanjob',
            name='pid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scanjob',
            name='estado',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('running', 'En progreso'), ('done', 'Completado'), ('error', 'Error'), ('cancelled', 'Cancelado')], default='pending', max_length=20),
        ),
    ]
