# Generated by Django 6.1 on 2026-08-25 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scan_network', '0002_scanjob_pid_alter_scanjob_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanjob',
            name='estado',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('running', 'En progreso'), ('done', 'Completado'), ('error', 'Error')], default='pending', max_length=20),
        ),
    ]
