# Generated by Django 6.1 on 2026-08-26 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scan_network', '0003_alter_scanjob_estado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scanjob',
            options={'ordering': ['-creado'], 'verbose_name': 'Network Scan', 'verbose_name_plural': 'Networks Scans'},
        ),
    ]
