# Generated by Django 6.1 on 2026-08-27 02:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileScanJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('archivo', models.FileField(upload_to='file_scans/%Y/%m/%d/')),
                ('nombre_original', models.CharField(max_length=255)),
                ('extension', models.CharField(blank=True, default='', max_length=20)),
                ('tamano_bytes', models.BigIntegerField(default=0)),
                ('hash_md5', models.CharField(blank=True, default='', max_length=32)),
                ('hash_sha1', models.CharField(blank=True, default='', max_length=40)),
                ('hash_sha256', models.CharField(blank=True, default='', max_length=64)),
                ('estado', models.CharField(choices=[('pending', 'Pendiente'), ('running', 'En progreso'), ('done', 'Completado'), ('error', 'Error')], default='pending', max_length=20)),
                ('veredicto', models.CharField(blank=True, choices=[('limpio', 'Limpio'), ('sospechoso', 'Sospechoso'), ('malicioso', 'Malicioso'), ('', 'Sin analizar')], default='', max_length=20)),
                ('detalles', models.JSONField(blank=True, default=dict)),
                ('resultado', models.TextField(blank=True, default='')),
                ('error_msg', models.TextField(blank=True, default='')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='file_scan_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Escaneo de archivo',
                'verbose_name_plural': 'Escaneos de archivos',
                'ordering': ['-creado'],
            },
        ),
    ]
