# Generated by Django 6.1 on 2026-08-25 01:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], default='info', max_length=10)),
                ('mensaje', models.CharField(max_length=500)),
                ('detalle', models.TextField(blank=True, default='')),
                ('origen', models.CharField(blank=True, default='', max_length=100)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='app_log_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creado'],
                'indexes': [models.Index(fields=['-creado'], name='logs_logent_creado_c811a6_idx'), models.Index(fields=['nivel'], name='logs_logent_nivel_9f79da_idx')],
            },
        ),
    ]
