# Generated by Django 6.1 on 2026-08-26 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logentry',
            options={'ordering': ['-creado'], 'verbose_name': 'Log', 'verbose_name_plural': 'Logs'},
        ),
    ]
