# Generated by Django 6.1 on 2026-08-25 02:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DnsScanJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target', models.CharField(max_length=255)),
                ('fuentes', models.CharField(choices=[('all', 'Todas las fuentes'), ('passive', 'Solo pasivas'), ('active', 'Activas (bruteforce DNS)')], default='all', max_length=20)),
                ('resolve', models.CharField(choices=[('resolve', 'Resolver IPs (mostrar solo activos)'), ('no_resolve', 'No resolver (más rápido)')], default='resolve', max_length=20)),
                ('wordlist', models.CharField(blank=True, choices=[('', 'Ninguna (solo fuentes pasivas)'), ('common', 'subdomains-top1million-5000.txt'), ('medium', 'subdomains-top1million-20000.txt'), ('big', 'subdomains-top1million-110000.txt')], default='', max_length=20)),
                ('estado', models.CharField(choices=[('pending', 'Pendiente'), ('running', 'En progreso'), ('done', 'Completado'), ('error', 'Error')], default='pending', max_length=20)),
                ('resultado', models.TextField(blank=True, default='')),
                ('total_subdominios', models.PositiveIntegerField(default=0)),
                ('error_msg', models.TextField(blank=True, default='')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creado'],
            },
        ),
    ]
