# Generated by Django 6.1 on 2026-08-26 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dns_subfinder', '0002_dnsscanjob_pid_alter_dnsscanjob_estado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dnsscanjob',
            options={'ordering': ['-creado'], 'verbose_name': 'Subfinder DNS', 'verbose_name_plural': 'Subfinder DNS'},
        ),
    ]
