# Generated by Django 6.1 on 2026-08-26 20:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanWeb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(max_length=255)),
                ('herramienta', models.CharField(choices=[('nuclei', 'Nuclei'), ('wpscan', 'WPScan'), ('nikto', 'Nikto')], max_length=20)),
                ('estado', models.CharField(choices=[('pending', 'Pendiente'), ('running', 'En progreso'), ('done', 'Completado'), ('error', 'Error'), ('cancelled', 'Cancelado')], default='pending', max_length=20)),
                ('opciones', models.JSONField(blank=True, default=dict)),
                ('resultado', models.TextField(blank=True, null=True)),
                ('error_msg', models.TextField(blank=True, null=True)),
                ('pid', models.IntegerField(blank=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scan_web_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Escaneo web',
                'verbose_name_plural': 'Escaneos web',
                'ordering': ['-creado'],
            },
        ),
    ]
